In [23]:
PATCHES_PATH_ON_SERVER = '/med-i_data/Data/Amoon/HDH_patches/'
LOCAL_DATA_DIR = '../data'

import os 
from os.path import join
if not os.path.isdir(LOCAL_DATA_DIR):
    os.mkdir(LOCAL_DATA_DIR)

import sys 
sys.path.append('../')
from src.data.exact.server import get_sftp, get_ssh
#sftp = get_sftp()
#sftp.listdir(PATCHES_PATH_ON_SERVER)
#
#sftp.get(f'{PATCHES_PATH_ON_SERVER}/meta_data.npz', join(LOCAL_DATA_DIR, 'meta_data.npz'))


In [24]:
import scp
ssh_conn = get_ssh().get_transport() 

def progress(filename, size, sent):
    sys.stdout.write("%s\'s progress: %.2f%%   \r" % (filename, float(sent)/float(size)*100) )

scp_client = scp.SCPClient(ssh_conn, progress=progress)
scp_client.get(PATCHES_PATH_ON_SERVER, LOCAL_DATA_DIR, recursive=True)

scp.get(ssh_conn, PATCHES_PATH_ON_SERVER, LOCAL_DATA_DIR, recursive=True)

In [58]:
for fpath in os.listdir(
    join(LOCAL_DATA_DIR, 'HDH_patches', 'bm_coor_oriented')):
    if not "data" in fpath:
        continue
    import re

    patient_id, core_id, patch_id = re.match(
        "P(\d+)_c(\d+)_p(\d+)_data.npy", fpath
    ).groups()
    print(patient_id)

2078
2063
2043
2054
2076
2089
2036
2065
2059
2002
2004
2041
2064
2015
2066
2081
2097
2085
2054
2045
2055
2009
2051
2074
2050
2035
2032
2056
2075
2003
2058
2006
2087
2030
2007
2068
2021
2031
2071
2022
2069
2082
2057
2055
2046
2067
2061
2078
2034
2034
2022
2056
2075
2082
2066
2003
2067
2002
2083
2054
2042
2099
2013
2053
2050
2044
2075
2059
2009
2033
2098
2080
2067
2095
2089
2070
2094
2060
2087
2075
2078
2069
2011
2012
2027
2096
2089
2059
2018
2030
2092
2074
2047
2090
2044
2043
2081
2050
2035
2013
2093
2052
2089
2081
2045
2086
2095
2082
2003
2075
2018
2084
2003
2052
2072
2039
2038
2085
2027
2037
2052
2061
2094
2034
2013
2057
2032
2003
2056
2018
2018
2030
2033
2058
2031
2068
2047
2032
2095
2062
2034
2094
2060
2090
2030
2082
2009
2052
2034
2041
2014
2067
2061
2002
2089
2037
2029
2071
2027
2065
2076
2033
2002
2030
2022
2097
2080
2075
2027
2007
2003
2018
2063
2072
2016
2045
2099
2085
2064
2099
2032
2099
2067
2018
2067
2055
2037
2007
2004
2030
2090
2021
2030
2046
2092
2035
2061
2069
2015
2012


In [28]:
import numpy as np 
metadata = np.load(join(LOCAL_DATA_DIR, 'HDH_patches', 'meta_data.npz'))

In [55]:
metadata['labels']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [34]:
list(metadata.keys())

['rf_files',
 'needle_files',
 'prostate_files',
 'patient_id',
 'core_locs',
 'labels',
 'gleasons',
 'involvements',
 'core_lengths',
 'pr_volumes',
 'psas',
 'depths',
 'naxs',
 'nlts',
 'ddxs',
 'rfxs',
 'rfys']

In [66]:
list(metadata.keys())

['rf_files',
 'needle_files',
 'prostate_files',
 'patient_id',
 'core_locs',
 'labels',
 'gleasons',
 'involvements',
 'core_lengths',
 'pr_volumes',
 'psas',
 'depths',
 'naxs',
 'nlts',
 'ddxs',
 'rfxs',
 'rfys']

In [61]:
metadata['patient_id']

array([2001, 2001, 2001, 2001, 2001, 2002, 2002, 2002, 2002, 2002, 2002,
       2003, 2003, 2003, 2003, 2003, 2003, 2003, 2004, 2004, 2004, 2004,
       2004, 2004, 2004, 2004, 2006, 2006, 2006, 2006, 2006, 2006, 2006,
       2007, 2007, 2007, 2007, 2007, 2007, 2008, 2008, 2008, 2009, 2009,
       2009, 2009, 2011, 2011, 2011, 2011, 2012, 2012, 2012, 2012, 2012,
       2012, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2014, 2014,
       2014, 2014, 2014, 2014, 2014, 2015, 2015, 2015, 2015, 2015, 2015,
       2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2017, 2017, 2017,
       2017, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2019,
       2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2021, 2021, 2021,
       2021, 2021, 2021, 2021, 2021, 2022, 2022, 2022, 2022, 2022, 2022,
       2022, 2022, 2022, 2024, 2024, 2025, 2025, 2027, 2027, 2027, 2027,
       2027, 2027, 2027, 2027, 2027, 2027, 2028, 2028, 2028, 2028, 2028,
       2028, 2028, 2028, 2028, 2029, 2029, 2029, 20

In [65]:
i = 5
np.where(metadata['patient_id'] == metadata['patient_id'][i])[0].tolist().index(i)

0

In [59]:
metadata

In [53]:
path = metadata['rf_files'][0]


In [54]:
path.split('\\')[-1]

'RF_A2_LML_45.dat'

In [37]:
metadata.allow_pickle = True

In [38]:
metadata['core_locs']

array(['LML', 'RBL', 'RBM', 'RMM', 'RA', 'LBM', 'RBL', 'RBM', 'RML',
       'RMM', 'RA', 'LBL', 'LBM', 'LML', 'LA', 'RBL', 'RML', 'RA', 'LBL',
       'LBM', 'LML', 'LMM', 'LA', 'RBL', 'RBM', 'RML', 'LBL', 'LBM', 'LA',
       'RBL', 'RBM', 'RML', 'RMM', 'LBM', 'LA', 'RBL', 'RBM', 'RML', 'RA',
       'LBL', 'LML', 'LA', 'LBM', 'RML', 'RMM', 'RA', 'LML', 'LMM', 'LA',
       'RMM', 'LBM', 'LML', 'LA', 'RBL', 'RBM', 'RMM', 'LBL', 'LBM',
       'LMM', 'LA', 'RBL', 'RBM', 'RML', 'RMM', 'LBL', 'LML', 'LMM',
       'RBL', 'RBM', 'RMM', 'RA', 'LBM', 'LML', 'RBL', 'RBM', 'RML',
       'RMM', 'LBM', 'LML', 'LMM', 'RBL', 'RBM', 'RML', 'RMM', 'RAM',
       'LBL', 'LML', 'LMM', 'RBL', 'LBL', 'LBM', 'LML', 'LA', 'RBL',
       'RBM', 'RML', 'RMM', 'RA', 'LBL', 'LBM', 'LML', 'LMM', 'LA', 'RBL',
       'RML', 'RMM', 'RA', 'LBL', 'LBM', 'LMM', 'LA', 'RBM', 'RML', 'RMM',
       'RA', 'LBL', 'LBM', 'LML', 'LMM', 'LA', 'RBM', 'RML', 'RMM', 'RA',
       'LA', 'RBM', 'LBM', 'LML', 'LBL', 'LBM', 'LML', 'LMM', '

In [18]:
sftp.chdir(PATCHES_PATH_ON_SERVER + '/bm_coor_oriented')
sftp.get(sftp.listdir()[0], join(LOCAL_DATA_DIR, sftp.listdir()[1]))

In [17]:
np.load(join('/home/paulw/projects/TRUSnet-1/data/HDH_patches/P2001_c0_p3_mask.npy'))

array([[nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan]])